### ISSUE TITLE
Unable to update to 1.4.3 - it looks successful, but isn't?

### ISSUE THREAD

**Issue by weaverryan** [symfony/symfony-installer#212]
<img width="699" alt="screen shot 2015-11-30 at 9 17 56 pm" src="https://cloud.githubusercontent.com/assets/121003/11490582/e61e0232-97a7-11e5-95fd-1fed566c9e67.png">

This may be something I'm doing wrong, but I couldn't figure out what was going on. It *looks* like it's updating, but it isn't actually getting the new version.

Anyone else?

**Comment by themccallister** [comment]
Same thing here @weaverryan. Also installing 3.0 throws this error: https://github.com/symfony/symfony/issues/16770

https://www.dropbox.com/s/xym55gzh1f5gkh7/Screenshot%202015-11-30%2019.39.32.png?dl=0

**Comment by weaverryan** [comment]
That error was fixed in #206, but that's only included in 1.4.2.

What's interesting is that you *also* can't update - but your update is from 1.4.1 to 1.4.2, whereas mine is from 1.4.2 to 1.4.3. I assumed it was a problem with 1.4.3. It's also odd that your installer doesn't know that 1.4.3 is actually the newest version.

**Comment by patrick-mcdougle** [comment]
In case it's helpful, I was able to upgrade successfully from 1.3.3 to 1.4.3.

**Comment by weaverryan** [comment]
@patrick-mcdougle that certainly makes the issue more interesting :)

**Comment by ogizanagi** [comment]
@weaverryan : I had the same issue many times \o/ ...and it's not since last releases...

In fact, the installer is not incriminated I guess, as you'll get the wrong version too by doing this:

```
curl -LsS http://symfony.com/installer -o symfony.phar
php symfony.phar --version
```

Something strange (it isn't the case right now, both give me 1.4.1) is that I also have this issue in the past, but downloading it with Chrome browser gave me the right version while curl gave me an oldest one.

**Comment by javiereguiluz** [comment]
This is the basic working of the `self-update` logic:

```php
$isUpdated = false;
$remoteVersion = @file_get_contents('http://get.symfony.com/symfony.version');

if (version_compare($localVersion, $remoteVersion, '>=')) {
    echo "Symfony Installer is already up to date.";
    $isUpdated = true;
} else {
    echo "// updating to $remoteVersion version";
}

return $isUpdated;
```

The strange thing is:

  * If I use a browser to visit `http://get.symfony.com/symfony.version`, a file is downloaded and its contents are `1.4.3`
  * If I do `file_get_contents('http://get.symfony.com/symfony.version')`, the result is `1.4.1`
  * If I do `(new \GuzzleHttp\Client())->get('http://get.symfony.com/symfony.version')->getBody()`, the result is `1.4.1` too.

I'm pinging @lyrixx in case this has something to do with the symfony.com server. Thanks!

**Comment by javiereguiluz** [comment]
I've found this:

```
$ curl http://get.symfony.com/symfony.version
1.4.1

$ curl --compressed http://get.symfony.com/symfony.version
1.4.3
```

Any thought to solve this?

**Comment by Pierstoval** [comment]
Same for me, curl without compressed:

```bash
$ curl -i http://get.symfony.com/symfony.version
HTTP/1.1 200 OK
Content-Type: application/octet-stream
Content-Length: 5
Connection: keep-alive
Date: Sat, 28 Nov 2015 09:40:30 GMT
Last-Modified: Fri, 27 Nov 2015 12:03:30 GMT
ETag: "1e6dbfaaa068a191cfd257c013ddd699"
Accept-Ranges: bytes
Server: AmazonS3
Age: 73797
X-Cache: Hit from cloudfront
Via: 1.1 dbde8ac00ce406599a623c34e6eb8a7b.cloudfront.net (CloudFront)
X-Amz-Cf-Id: dNIl-eckbJMiJ4B8CUFXRt6E2lku6v_zvf9Y-RLWU7mtL_72DQvopw==

1.4.1
```

And curl with compressed:

```bash
$ curl -i http://get.symfony.com/symfony.version --compressed
HTTP/1.1 200 OK
Content-Type: application/octet-stream
Content-Length: 5
Connection: keep-alive
Date: Tue, 01 Dec 2015 09:38:47 GMT
Last-Modified: Mon, 30 Nov 2015 22:05:45 GMT
ETag: "ce4c72d73e8b7b3c2bd84f389213133c"
Accept-Ranges: bytes
Server: AmazonS3
Age: 128
X-Cache: Hit from cloudfront
Via: 1.1 a3fcfba3880bfa2744f8dc329465e037.cloudfront.net (CloudFront)
X-Amz-Cf-Id: U-M16SfdxGRS73Kws8xOxKDMjNAUgXTiwg7dgd_mH0i0K2ug9M2E_g==

1.4.3
```

**Comment by lyrixx** [comment]
It's all about cache. I'm going to reset the cache asap.

**Comment by Pierstoval** [comment]
Is there a solution for the installer-builder to invalidate the cache automatically?

**Comment by stof** [comment]
@Pierstoval the installer does not have a local cache. the caching is most probably between the S3 and Cloudfront. this means it is something to be solved on the server side.

**Comment by lyrixx** [comment]
> Is there a solution for the installer-builder to invalidate the cache automatically?

I think so. We are using aws S3 + cloud front + aws-php-sdk.

I have not time right now to find how to send an invalidation request with the SDK. So If someone could give me a little snippet,  it could be very nice ;)

**Comment by Pierstoval** [comment]
@stof I'm not talking about the installer itself, but about the script that generates the phar file in the server. After `box build`, maybe one could add something that invalidate the cache for this specific file :confused:

**Comment by lyrixx** [comment]
from **my** location, the cache is invalidated:

```
>(4)[/home/greg] curl http://get.symfony.com/symfony.version  && echo
1.4.3
>(4)[/home/greg] curl http://get.symfony.com/symfony.version --compressed  && echo
1.4.3
```

But AWS keep saying the invalidation is still "InProgress".

So I should be OK in a couple of minutes.

**Comment by xabbuh** [comment]
@lyrixx Is that something that will now happen automatically when a new version of the installer is published?

**Comment by lyrixx** [comment]
It's not automated yet :-(

**Comment by weaverryan** [comment]
Cache not updated where I am in the USA yet: it just advertised downloading 1.4.4, but I'm still on 1.4.2.

**Comment by javiereguiluz** [comment]
@weaverryan that may be an unrelated problem. On my side the version is correctly detected, the installer says *"installing the new version"* ... but nothing gets installed and no error message is displayed. I'm trying to debug the problem but I'm going crazy :(

**Comment by weaverryan** [comment]
@javiereguiluz you're right:

```
curl http://get.symfony.com/symfony.version  && echo
1.4.4
```

So, the version file *is* up to date, no caching issues. BUT, if I download the installer directly:

```
wget http://symfony.com/installer
php installer --version
1.4.2
```

Is the problem simply that the /installer file on symfony.com has some sort of caching?

**Comment by Pierstoval** [comment]
It's all about cache invalidation, they said :laughing:

**Comment by ogizanagi** [comment]
I know this has already been raised in the past (https://github.com/symfony/symfony-installer/issues/116#issuecomment-100509769), but what about using Github's API for this instead ?
Using [`https://api.github.com/repos/symfony/symfony-installer/releases/latest`](https://api.github.com/repos/symfony/symfony-installer/releases/latest), you'll get the latest release. 
You can [attach artifacts to a release](https://github.com/blog/1547-release-your-software#creating-releases), and can be automated [once again using Github's API](https://developer.github.com/v3/repos/releases/#upload-a-release-asset).

Here's what looks like a release with its artifacts (`assets` key):
- https://api.github.com/repos/Behat/Behat/releases/latest

**Comment by lyrixx** [comment]
I'm going to discuss about the Github Api with @fabpot today.

**Comment by weaverryan** [comment]
The good news is that I *was* able to update to 1.4.4 for now. Temporarily the problem was solved, but I think we should keep this open until it's properly solved.

Thanks @lyrixx

**Comment by cjunge-work** [comment]
Just a note to say still happening. And, I got a weird result:

    $ symfony self-update
    // updating Symfony Installer to 1.4.0
     version

    $ symfony --version
    Symfony Installer version 1.5.0

    $ curl http://get.symfony.com/symfony.version  && echo
    1.5.0

    $ curl http://get.symfony.com/symfony.version --compressed  && echo
    1.5.0

Version installed is correct, but that first version number is wrong.

**Comment by javiereguiluz** [comment]
I'm closing it as fixed. We've made some change to the internal publishing workflow of the installer packages and everything seems to work as expected. I've just run symfony self-update and got the shiny new 1.5.1 version.

If it doesn't work for any of you, please reopen this issue. Thanks!
